import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,Check,ChevronRight,HeartHandshake,Menu,ShieldCheck,Sparkles,Stethoscope,X}from'lucide-react';
import'./style.css';
import'./build.css';
import'./footer.css';

const steps=['Your needs','Foot details','Review'];

function Intake({close}){
 const[step,setStep]=useState(0),[sent,setSent]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
 const[form,setForm]=useState({path:'For myself',name:'',email:'',phone:'',goal:'',details:'',consent:false,company:''});
 const update=e=>{const{name,type,checked,value}=e.target;setForm({...form,[name]:type==='checkbox'?checked:value});setError('')};
 const advance=()=>{if(step===1&&(!form.name.trim()||!form.email.trim()||!form.goal)){setError('Please complete your name, email, and request type.');return}setError('');setStep(step+1)};
 const submit=async()=>{if(!form.consent){setError('Please confirm that we may contact you about this request.');return}setSubmitting(true);setError('');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'We could not send your request.');setSent(true)}catch(requestError){setError(requestError.message||'We could not send your request. Please email care@openfootlab.com.')}finally{setSubmitting(false)}};
 if(sent)return <div className="modal"><div className="done"><button className="close" onClick={close} aria-label="Close"><X/></button><div className="done-icon"><Check/></div><p className="eyebrow">REQUEST RECEIVED</p><h2>Thank you for reaching out.</h2><p>Your request was sent to OpenFootLab. A real person will review it and follow up using the contact information you provided.</p><p>Questions? <a href="mailto:care@openfootlab.com">care@openfootlab.com</a></p><button className="primary" onClick={close}>Return home</button></div></div>;
 return <div className="modal"><div className="intake">
  <button className="close" onClick={close} aria-label="Close"><X/></button><p className="eyebrow">START YOUR FOOT PROFILE</p><h2>Let’s understand what you need.</h2><div className="progress">{steps.map((s,i)=><span className={i<=step?'active':''} key={s}>{i+1}. {s}</span>)}</div>
  {step===0&&<div className="screen"><label>Who is this request for?</label><div className="choice">{['For myself','For someone I care for','For a patient'].map(x=><button key={x} className={form.path===x?'selected':''} onClick={()=>setForm({...form,path:x})}>{x}<ChevronRight/></button>)}</div></div>}
  {step===1&&<div className="screen fields"><label>Name<input name="name" value={form.name} onChange={update} placeholder="Your name" autoComplete="name"/></label><label>Email<input name="email" value={form.email} onChange={update} placeholder="you@example.com" type="email" autoComplete="email"/></label><label>Phone <span>(optional)</span><input name="phone" value={form.phone} onChange={update} placeholder="Your phone number" type="tel" autoComplete="tel"/></label><label>What would you like help with?<select name="goal" value={form.goal} onChange={update}><option value="">Select one</option><option>Personalized insert</option><option>Toe filler or accommodation</option><option>Prototype for clinician review</option><option>Something else</option></select></label></div>}
  {step===2&&<div className="screen fields"><label>Anything you want us to understand?<textarea name="details" value={form.details} onChange={update} maxLength="1200" placeholder="Tell us generally about fit, comfort, footwear, or your goal."/></label><label className="website-field" aria-hidden="true">Company<input name="company" value={form.company} onChange={update} tabIndex="-1" autoComplete="off"/></label><div className="notice"><ShieldCheck/><span><b>Please protect your privacy:</b> do not submit medical records, wound photographs, diagnoses, or urgent medical concerns through this form.</span></div><label className="consent"><input type="checkbox" name="consent" checked={form.consent} onChange={update}/><span>I agree that OpenFootLab may contact me about this request.</span></label></div>}
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="actions">{step>0&&<button className="back" onClick={()=>{setError('');setStep(step-1)}} disabled={submitting}>Back</button>}<button className="primary" onClick={()=>step<2?advance():submit()} disabled={submitting}>{step<2?'Continue':submitting?'Sending…':'Send request'}{!submitting&&<ArrowRight/>}</button></div>
 </div></div>
}

function App(){
 const[open,setOpen]=useState(false),[nav,setNav]=useState(false);
 return <><header><a className="brand" href="#"><span className="mark">OF</span><span>OPENFOOTLAB<small>PERSONALIZED FOOT SUPPORT</small></span></a><nav className={nav?'show':''}><a href="#process">How it works</a><a href="#build">Built by design</a><a href="#care">What we make</a><a href="#clinicians">For clinicians</a></nav><button className="navcta" onClick={()=>setOpen(true)}>Start your foot profile</button><button className="menu" onClick={()=>setNav(!nav)}>{nav?<X/>:<Menu/>}</button></header>
 <main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow"><span></span>PERSONALIZED. PRACTICAL. HUMAN.</p><h1>Custom-made support for <em>feet at risk.</em></h1><p className="lead">OpenFootLab turns real needs into personalized inserts and foot-support prototypes through a clear, collaborative process.</p><div className="hero-actions"><button className="primary" onClick={()=>setOpen(true)}>Start your foot profile<ArrowRight/></button><a href="#build">See how it’s built</a></div><div className="trust"><span><Check/>Human review</span><span><Check/>Built locally</span><span><Check/>Clinician-friendly</span></div></div>
  <div className="hero-visual"><div className="orbit one"></div><div className="orbit two"></div><div className="insole"><div className="mesh"></div><span>01</span></div><div className="float-card"><Sparkles/><div><b>Designed around you</b><small>Not pulled from a shelf.</small></div></div></div></section>
  <section className="statement" id="story"><p>Better support starts with better listening.</p><h2>You show us the need.<br/>We help shape the solution.</h2></section>
  <section className="process" id="process"><div><p className="eyebrow">A SIMPLE PATH FORWARD</p><h2>From your story<br/>to something tangible.</h2><p>No technical vocabulary required. We guide each step and keep the process clear.</p></div><div className="steps">{[['01','Tell us what you need','Complete a short, friendly profile about the person, footwear and goal.'],['02','We review together','A real person reviews the request and identifies the right next step.'],['03','We design and build','We translate the need into a manufacturable prototype for review.'],['04','Fit. Learn. Refine.','Feedback becomes part of the design—not an afterthought.']].map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
  <section className="build" id="build">
   <div className="build-head"><div><p className="eyebrow">QUALITY BY DESIGN</p><h2>Built to the foot.<br/>Layer by layer.</h2></div><p>Every layer has a job. We combine a light inspection surface, tuned TPU support, engineered lattice and a stable base into one build shaped around the person—not pulled from a shelf.</p></div>
   <div className="exploded"><img src="/images/openfootlab-exploded-build.webp" alt="Exploded view of an OpenFootLab insert showing spacer mesh, TPU support, lattice and base layers" loading="lazy"/><div className="layer-key">{[['01','3D spacer mesh','Light, breathable contact surface designed for comfort and easier visual inspection.'],['02','TPU 90A support','Printed geometry tuned for shape, flex and localized accommodation.'],['03','Engineered lattice','Variable structure places give and support where the build calls for it.'],['04','Structural base','A stable foundation that keeps the complete insert working as one system.']].map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></div>
   <div className="build-path">{[['01','Understand','The foot, footwear and goal.'],['02','Design','Geometry shaped to the need.'],['03','Manufacture','Materials built with intention.'],['04','Review','Fit, learn and refine.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div>
  </section>
  <section className="builds">
   <div className="builds-intro"><p className="eyebrow">BUILT FOR A REASON</p><h2>See the support<br/>before you wear it.</h2><p>These build views help clients understand that an accommodation is designed into the insert—not added as an afterthought.</p></div>
   <div className="build-grid">
    <article className="build-card"><img src="/images/openfootlab-layered-insert.webp" alt="Cutaway personalized insert with tan spacer mesh, toe accommodation, TPU and lattice layers" loading="lazy"/><div><span>TOE ACCOMMODATION</span><h3>Space restored with purpose.</h3><p>An integrated filler and layered build shaped to occupy missing volume while maintaining a light, inspectable contact surface.</p></div></article>
    <article className="build-card"><img src="/images/openfootlab-ulcer-offloading.webp" alt="Ulcer-offloading insert concept with a feathered localized pressure-relief pocket" loading="lazy"/><div><span>LOCALIZED OFFLOADING</span><h3>Relief designed into the structure.</h3><p>A recessed pocket, feathered transition and tuned surrounding support create a purposeful accommodation around a defined area.</p></div></article>
   </div>
  </section>
  <section className="care" id="care"><div className="care-photo"><div className="rings"></div><span>MADE WITH PURPOSE</span></div><div><p className="eyebrow">WHAT WE MAKE</p><h2>Thoughtful support for real feet.</h2><p>We develop personalized foot-support products and prototypes with attention to fit, pressure, materials and the person who will use them.</p><ul><li><Check/>Personalized inserts</li><li><Check/>Toe fillers and accommodations</li><li><Check/>Clinician-directed prototypes</li><li><Check/>Rapid design refinement</li></ul><p className="fine">OpenFootLab products are not a substitute for diagnosis, emergency care, or treatment by a licensed medical professional.</p></div></section>
  <section className="clinician" id="clinicians"><div className="icon"><Stethoscope/></div><p className="eyebrow">FOR CLINICIANS & PRACTICES</p><h2>A responsive fabrication partner.</h2><p>Bring us the clinical objective. We help translate it into a reviewable prototype while keeping communication direct and the workflow easy to follow.</p><button className="light" onClick={()=>setOpen(true)}>Start a clinician request<ArrowRight/></button></section>
  <section className="founder"><HeartHandshake/><blockquote>“I know what it feels like when a foot problem becomes the center of your life. OpenFootLab is built to make the next step clearer, more personal, and more useful.”</blockquote><p>DONOVAN MACKEY <span>Founder · Type 1 diabetic</span></p></section>
  <section className="final"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Let’s start with your foot.</h2><button className="primary" onClick={()=>setOpen(true)}>Start your foot profile<ArrowRight/></button><p>Questions? <a href="mailto:care@openfootlab.com">care@openfootlab.com</a> · <a href="tel:15615327120">561.532.7120</a></p></section>
 </main><footer className="site-footer"><div className="footer-brand"><div className="brand"><span className="mark">OF</span><span>OPENFOOTLAB</span></div><p>Personalized foot support, built with care.</p></div><a className="engine-link" href="https://opendiabetic.com/" target="_blank" rel="noopener noreferrer"><span>BUILD ENGINE</span><strong>OpenDiabetic <ArrowRight/></strong><small>Daily foot intelligence → personalized design → made-to-fit manufacturing.</small></a><p className="footer-meta">© 2026 OpenFootLab<br/>Jupiter, Florida</p></footer>{open&&<Intake close={()=>setOpen(false)}/>}</>
}
createRoot(document.getElementById('root')).render(<App/>);
