import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,Building2,Check,ChevronRight,HeartHandshake,MapPin,Menu,Route,ShieldCheck,Sparkles,Stethoscope,X}from'lucide-react';
import'./style.css';
import'./build.css';
import'./footer.css';
import'./local.css';

const steps=['Your needs','Foot details','Review'];

function Intake({close}){
 const[step,setStep]=useState(0),[sent,setSent]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
 const[form,setForm]=useState({path:'For myself',name:'',email:'',phone:'',area:'',goal:'',details:'',consent:false,company:''});
 const update=e=>{const{name,type,checked,value}=e.target;setForm({...form,[name]:type==='checkbox'?checked:value});setError('')};
 const advance=()=>{if(step===1&&(!form.name.trim()||!form.email.trim()||!form.goal)){setError('Please complete your name, email, and request type.');return}setError('');setStep(step+1)};
 const submit=async()=>{if(!form.consent){setError('Please confirm that we may contact you about this request.');return}setSubmitting(true);setError('');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'We could not send your request.');setSent(true)}catch(requestError){setError(requestError.message||'We could not send your request. Please email care@openfootlab.com.')}finally{setSubmitting(false)}};
 if(sent)return <div className="modal"><div className="done"><button className="close" onClick={close} aria-label="Close"><X/></button><div className="done-icon"><Check/></div><p className="eyebrow">REQUEST RECEIVED</p><h2>Thank you for reaching out.</h2><p>Your request was sent to OpenFootLab. A real person will review it and follow up using the contact information you provided.</p><p>Questions? <a href="mailto:care@openfootlab.com">care@openfootlab.com</a></p><button className="primary" onClick={close}>Return home</button></div></div>;
 return <div className="modal"><div className="intake">
  <button className="close" onClick={close} aria-label="Close"><X/></button><p className="eyebrow">START A LOCAL REQUEST</p><h2>Let’s understand what you need.</h2><div className="progress">{steps.map((s,i)=><span className={i<=step?'active':''} key={s}>{i+1}. {s}</span>)}</div>
  {step===0&&<div className="screen"><label>Who is this request for?</label><div className="choice">{['For myself','For someone I care for','For a patient'].map(x=><button key={x} className={form.path===x?'selected':''} onClick={()=>setForm({...form,path:x})}>{x}<ChevronRight/></button>)}</div></div>}
  {step===1&&<div className="screen fields"><label>Name<input name="name" value={form.name} onChange={update} placeholder="Your name" autoComplete="name"/></label><label>Email<input name="email" value={form.email} onChange={update} placeholder="you@example.com" type="email" autoComplete="email"/></label><label>Phone <span>(optional)</span><input name="phone" value={form.phone} onChange={update} placeholder="Your phone number" type="tel" autoComplete="tel"/></label><label>Service area <span>(optional)</span><select name="area" value={form.area} onChange={update}><option value="">Select one</option><option>Palm Beach County</option><option>Martin County</option><option>Outside our local service area</option></select></label><label>What would you like help with?<select name="goal" value={form.goal} onChange={update}><option value="">Select one</option><option>Personalized insert</option><option>Toe filler or accommodation</option><option>Mobile fit visit</option><option>FLO or FootLabOS monitoring</option><option>Clinician or practice partnership</option><option>Prototype for clinician review</option><option>Something else</option></select></label></div>}
  {step===2&&<div className="screen fields"><label>Anything you want us to understand?<textarea name="details" value={form.details} onChange={update} maxLength="1200" placeholder="Tell us generally about fit, comfort, footwear, or your goal."/></label><label className="website-field" aria-hidden="true">Company<input name="company" value={form.company} onChange={update} tabIndex="-1" autoComplete="off"/></label><div className="notice"><ShieldCheck/><span><b>Please protect your privacy:</b> do not submit medical records, wound photographs, diagnoses, or urgent medical concerns through this form.</span></div><label className="consent"><input type="checkbox" name="consent" checked={form.consent} onChange={update}/><span>I agree that OpenFootLab may contact me about this request.</span></label></div>}
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="actions">{step>0&&<button className="back" onClick={()=>{setError('');setStep(step-1)}} disabled={submitting}>Back</button>}<button className="primary" onClick={()=>step<2?advance():submit()} disabled={submitting}>{step<2?'Continue':submitting?'Sending…':'Send request'}{!submitting&&<ArrowRight/>}</button></div>
 </div></div>
}

function App(){
 const[open,setOpen]=useState(false),[nav,setNav]=useState(false);
 return <><header><a className="brand" href="#"><span className="mark">OF</span><span>OPENFOOTLAB<small>LOCAL FOOT SUPPORT + MANUFACTURING</small></span></a><nav className={nav?'show':''}><a href="#process">How it works</a><a href="#service">Local service</a><a href="#footlabos">FootLabOS</a><a href="#clinicians">For clinicians</a></nav><button className="navcta" onClick={()=>setOpen(true)}>Start a request</button><button className="menu" onClick={()=>setNav(!nav)} aria-label="Toggle navigation">{nav?<X/>:<Menu/>}</button></header>
 <main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow"><span></span>JUPITER OFFICE · PALM BEACH + MARTIN</p><h1>Local support for <em>feet at risk.</em></h1><p className="lead">OpenFootLab is a Jupiter-based foot technology and manufacturing partner. We coordinate local fit visits, build personalized inserts and keep the follow-through moving through FootLabOS and FLO.</p><div className="hero-actions"><button className="primary" onClick={()=>setOpen(true)}>Start a local request<ArrowRight/></button><a href="#service">Explore local service</a></div><div className="trust"><span><Check/>Jupiter office</span><span><Check/>Mobile local visits</span><span><Check/>Clinician-guided</span></div></div>
  <div className="hero-visual"><div className="orbit one"></div><div className="orbit two"></div><div className="insole"><div className="mesh"></div><span>01</span></div><div className="float-card"><Sparkles/><div><b>Designed around you</b><small>Not pulled from a shelf.</small></div></div></div></section>
  <section className="statement" id="story"><p>Better support starts with better listening.</p><h2>You show us the need.<br/>We help shape the solution.</h2></section>
  <section className="local-service" id="service">
   <div className="service-head"><p className="eyebrow">LOCAL, MOBILE, CONNECTED</p><h2>A full-service local partner—from first conversation to follow-through.</h2><p>OpenFootLab serves Palm Beach and Martin counties from our Jupiter office. We meet clients where the work happens: at home, at a participating doctor’s office, at a clinic, or at our office by appointment.</p></div>
   <div className="service-grid">
    <article><Building2/><span>01</span><h3>Jupiter office</h3><p>Our local base for review, design and manufacturing, with office visits available by appointment.</p></article>
    <article><Route/><span>02</span><h3>Mobile fit visits</h3><p>Local visits across Palm Beach and Martin counties, coordinated with the client and care team when clinician direction is appropriate.</p></article>
    <article><HeartHandshake/><span>03</span><h3>Complete follow-through</h3><p>Intake, manufacturing inputs, design, local production, delivery, feedback and refinement stay connected in one clear workflow.</p></article>
   </div>
   <div className="service-area"><MapPin/><div><strong>Local service area</strong><span>Jupiter · Tequesta · Palm Beach Gardens · West Palm Beach · Hobe Sound · Stuart · Palm City · Jensen Beach</span></div><button className="text-button" onClick={()=>setOpen(true)}>Request a visit<ArrowRight/></button></div>
  </section>
  <section className="process" id="process"><div><p className="eyebrow">A SIMPLE PATH FORWARD</p><h2>From your story<br/>to something tangible.</h2><p>No technical vocabulary required. We guide each step and keep the process clear.</p></div><div className="steps">{[['01','Tell us what you need','Complete a short, friendly profile about the person, footwear and goal.'],['02','We review together','A real person reviews the request and identifies the right next step.'],['03','We design and build','We translate the need into a manufacturable prototype for review.'],['04','Fit. Learn. Refine.','Feedback becomes part of the design—not an afterthought.']].map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
  <section className="footlabos" id="footlabos">
   <div className="os-intro"><p className="eyebrow">THE SYSTEM INSIDE OPENFOOTLAB</p><h2>Powered by <em>FootLabOS.</em></h2><p>FootLabOS connects the daily client experience to the people and manufacturing decisions behind every build. FLO makes the check-in simple; the Flight Sheet preserves what matters; the build record supports the next adjustment.</p><a className="light" href="https://footlabos.com/" target="_blank" rel="noopener noreferrer">Explore FootLabOS<ArrowRight/></a></div>
   <div className="os-grid">
    <article><span>FLO</span><h3>One-minute check-ins</h3><p>No app and no password. A secure link keeps the client loop simple and consistent.</p></article>
    <article><span>FLIGHT SHEET</span><h3>A living record</h3><p>Foot observations, footwear, build decisions, delivery notes and feedback stay connected over time.</p></article>
    <article><span>LOCAL BUILD</span><h3>Fit. Learn. Refine.</h3><p>Each approved adjustment becomes part of the manufacturing history instead of disappearing after delivery.</p></article>
   </div>
  </section>
  <section className="build" id="build">
   <div className="build-head"><div><p className="eyebrow">QUALITY BY DESIGN</p><h2>Built to the foot.<br/>Layer by layer.</h2></div><p>Every layer has a job. We combine a light inspection surface, tuned TPU support, engineered lattice and a stable base into one build shaped around the person—not pulled from a shelf.</p></div>
   <div className="exploded"><img src="/images/openfootlab-exploded-build.webp" alt="Exploded view of an OpenFootLab insert showing spacer mesh, TPU support, lattice and base layers" loading="lazy"/><div className="layer-key">{[['01','3D spacer mesh','Light, breathable contact surface designed for comfort and easier visual inspection.'],['02','TPU 90A support','Printed geometry tuned for shape, flex and localized accommodation.'],['03','Engineered lattice','Variable structure places give and support where the build calls for it.'],['04','Structural base','A stable foundation that keeps the complete insert working as one system.']].map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></div>
   <div className="build-path">{[['01','Understand','The foot, footwear and goal.'],['02','Design','Geometry shaped to the need.'],['03','Manufacture','Materials built with intention.'],['04','Review','Fit, learn and refine.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div>
  </section>
  <section className="builds">
   <div className="builds-intro"><p className="eyebrow">BUILT FOR A REASON</p><h2>See the support<br/>before you wear it.</h2><p>These build views help clients understand that an accommodation is designed into the insert—not added as an afterthought.</p></div>
   <div className="build-grid">
    <article className="build-card"><img src="/images/openfootlab-layered-insert.webp" alt="Cutaway personalized insert with tan spacer mesh, toe accommodation, TPU and lattice layers" loading="lazy"/><div><span>TOE ACCOMMODATION</span><h3>Space restored with purpose.</h3><p>An integrated filler and layered build shaped to occupy missing volume while maintaining a light, inspectable contact surface.</p></div></article>
    <article className="build-card"><img src="/images/openfootlab-ulcer-offloading.webp" alt="Ulcer-offloading insert concept with a feathered localized pressure-relief pocket" loading="lazy"/><div><span>LOCALIZED OFFLOADING</span><h3>Relief designed into the structure.</h3><p>A recessed pocket, feathered transition and tuned surrounding support create a purposeful accommodation around a defined area.</p></div></article>
   </div>
  </section>
  <section className="care" id="care"><div className="care-photo"><div className="rings"></div><span>MADE WITH PURPOSE</span></div><div><p className="eyebrow">WHAT WE MAKE</p><h2>Thoughtful support for real feet.</h2><p>We develop personalized foot-support products and prototypes with attention to fit, pressure, materials and the person who will use them.</p><ul><li><Check/>Personalized inserts</li><li><Check/>Toe fillers and accommodations</li><li><Check/>Clinician-directed prototypes</li><li><Check/>Rapid design refinement</li></ul><p className="fine">OpenFootLab products are not a substitute for diagnosis, emergency care, or treatment by a licensed medical professional.</p></div></section>
  <section className="clinician" id="clinicians"><div className="icon"><Stethoscope/></div><p className="eyebrow">FOR PODIATRISTS, CLINICIANS & PRACTICES</p><h2>Your local manufacturing and continuity partner.</h2><p>We can meet at the practice, capture the approved manufacturing inputs, build locally, coordinate delivery and preserve the feedback loop through FootLabOS. The licensed care team remains in control of diagnosis, treatment and clinical decisions.</p><div className="clinician-actions"><button className="light" onClick={()=>setOpen(true)}>Start a practice conversation<ArrowRight/></button><a href="mailto:care@openfootlab.com?subject=OpenFootLab%20practice%20partnership">care@openfootlab.com</a></div></section>
  <section className="founder"><HeartHandshake/><blockquote>“I know what it feels like when a foot problem becomes the center of your life. OpenFootLab is built to make the next step clearer, more personal, and more useful.”</blockquote><p>DONOVAN MACKEY <span>Founder · Type 1 diabetic</span></p></section>
  <section className="final"><p className="eyebrow">LOCAL SUPPORT STARTS HERE</p><h2>Tell us where you are and what you need.</h2><button className="primary" onClick={()=>setOpen(true)}>Start a local request<ArrowRight/></button><p>Jupiter office by appointment · Palm Beach + Martin counties<br/>Questions? <a href="mailto:care@openfootlab.com">care@openfootlab.com</a> · <a href="tel:15615327120">561.532.7120</a></p></section>
 </main><footer className="site-footer"><div className="footer-brand"><div className="brand"><span className="mark">OF</span><span>OPENFOOTLAB</span></div><p>Local foot support and personalized manufacturing.</p></div><a className="engine-link" href="https://footlabos.com/" target="_blank" rel="noopener noreferrer"><span>POWERED BY</span><strong>FootLabOS <ArrowRight/></strong><small>FLO check-ins → Flight Sheets → personalized design → local manufacturing.</small></a><p className="footer-meta">© 2026 OpenFootLab<br/>Jupiter office · By appointment<br/>Palm Beach + Martin counties</p></footer>{open&&<Intake close={()=>setOpen(false)}/>}</>
}
createRoot(document.getElementById('root')).render(<App/>);
