import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,Check,ChevronRight,HeartHandshake,Menu,ShieldCheck,Sparkles,Stethoscope,X}from'lucide-react';
import'./style.css';

const steps=['Your needs','Foot details','Review'];

function Intake({close}){
 const[step,setStep]=useState(0),[sent,setSent]=useState(false),[form,setForm]=useState({path:'For myself',name:'',email:'',goal:'',details:''});
 const update=e=>setForm({...form,[e.target.name]:e.target.value});
 if(sent)return <div className="modal"><div className="done"><button className="close" onClick={close}><X/></button><div className="done-icon"><Check/></div><p className="eyebrow">TESTNET COMPLETE</p><h2>Your path is ready.</h2><p>This demo did not transmit or store your information. In the live experience, an OpenFootLab team member will personally review your request and follow up.</p><button className="primary" onClick={close}>Return home</button></div></div>;
 return <div className="modal"><div className="intake">
  <button className="close" onClick={close}><X/></button><p className="eyebrow">OPENFOOTLAB TESTNET</p><h2>Let’s understand what you need.</h2><div className="progress">{steps.map((s,i)=><span className={i<=step?'active':''} key={s}>{i+1}. {s}</span>)}</div>
  {step===0&&<div className="screen"><label>Who is this request for?</label><div className="choice">{['For myself','For someone I care for','For a patient'].map(x=><button key={x} className={form.path===x?'selected':''} onClick={()=>setForm({...form,path:x})}>{x}<ChevronRight/></button>)}</div></div>}
  {step===1&&<div className="screen fields"><label>Name<input name="name" value={form.name} onChange={update} placeholder="Your name"/></label><label>Email<input name="email" value={form.email} onChange={update} placeholder="you@example.com" type="email"/></label><label>What would you like help with?<select name="goal" value={form.goal} onChange={update}><option value="">Select one</option><option>Personalized insert</option><option>Toe filler or accommodation</option><option>Prototype for clinician review</option><option>Something else</option></select></label></div>}
  {step===2&&<div className="screen fields"><label>Anything you want us to understand?<textarea name="details" value={form.details} onChange={update} placeholder="Tell us about fit, comfort, footwear, or your goal. Please do not enter urgent or highly sensitive medical information in this demo."/></label><div className="notice"><ShieldCheck/><span><b>Testnet privacy:</b> this prototype does not send or save your entry.</span></div></div>}
  <div className="actions">{step>0&&<button className="back" onClick={()=>setStep(step-1)}>Back</button>}<button className="primary" onClick={()=>step<2?setStep(step+1):setSent(true)}>{step<2?'Continue':'Complete demo'}<ArrowRight/></button></div>
 </div></div>
}

function App(){
 const[open,setOpen]=useState(false),[nav,setNav]=useState(false);
 return <><header><a className="brand" href="#"><span className="mark">OF</span><span>OPENFOOTLAB<small>PERSONALIZED FOOT SUPPORT</small></span></a><nav className={nav?'show':''}><a href="#process">How it works</a><a href="#care">What we make</a><a href="#clinicians">For clinicians</a><a href="#story">Our story</a></nav><button className="navcta" onClick={()=>setOpen(true)}>Start your foot profile</button><button className="menu" onClick={()=>setNav(!nav)}>{nav?<X/>:<Menu/>}</button></header>
 <main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow"><span></span>PERSONALIZED. PRACTICAL. HUMAN.</p><h1>Support made for the <em>foot in front of us.</em></h1><p className="lead">OpenFootLab turns real needs into personalized inserts and foot-support prototypes through a clear, collaborative process.</p><div className="hero-actions"><button className="primary" onClick={()=>setOpen(true)}>Start your foot profile<ArrowRight/></button><a href="#process">See how it works</a></div><div className="trust"><span><Check/>Human review</span><span><Check/>Built locally</span><span><Check/>Clinician-friendly</span></div></div>
  <div className="hero-visual"><div className="orbit one"></div><div className="orbit two"></div><div className="insole"><div className="mesh"></div><span>01</span></div><div className="float-card"><Sparkles/><div><b>Designed around you</b><small>Not pulled from a shelf.</small></div></div></div></section>
  <section className="statement" id="story"><p>Better support starts with better listening.</p><h2>You show us the need.<br/>We help shape the solution.</h2></section>
  <section className="process" id="process"><div><p className="eyebrow">A SIMPLE PATH FORWARD</p><h2>From your story<br/>to something tangible.</h2><p>No technical vocabulary required. We guide each step and keep the process clear.</p></div><div className="steps">{[['01','Tell us what you need','Complete a short, friendly profile about the person, footwear and goal.'],['02','We review together','A real person reviews the request and identifies the right next step.'],['03','We design and build','We translate the need into a manufacturable prototype for review.'],['04','Fit. Learn. Refine.','Feedback becomes part of the design—not an afterthought.']].map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
  <section className="care" id="care"><div className="care-photo"><div className="rings"></div><span>MADE WITH PURPOSE</span></div><div><p className="eyebrow">WHAT WE MAKE</p><h2>Thoughtful support for real feet.</h2><p>We develop personalized foot-support products and prototypes with attention to fit, pressure, materials and the person who will use them.</p><ul><li><Check/>Personalized inserts</li><li><Check/>Toe fillers and accommodations</li><li><Check/>Clinician-directed prototypes</li><li><Check/>Rapid design refinement</li></ul><p className="fine">OpenFootLab products are not a substitute for diagnosis, emergency care, or treatment by a licensed medical professional.</p></div></section>
  <section className="clinician" id="clinicians"><div className="icon"><Stethoscope/></div><p className="eyebrow">FOR CLINICIANS & PRACTICES</p><h2>A responsive fabrication partner.</h2><p>Bring us the clinical objective. We help translate it into a reviewable prototype while keeping communication direct and the workflow easy to follow.</p><button className="light" onClick={()=>setOpen(true)}>Start a clinician request<ArrowRight/></button></section>
  <section className="founder"><HeartHandshake/><blockquote>“I know what it feels like when a foot problem becomes the center of your life. OpenFootLab is built to make the next step clearer, more personal, and more useful.”</blockquote><p>DONOVAN MACKEY <span>Founder · Type 1 diabetic</span></p></section>
  <section className="final"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Let’s start with your foot.</h2><button className="primary" onClick={()=>setOpen(true)}>Start your foot profile<ArrowRight/></button><p>Questions? <a href="mailto:build@openfootlab.com">build@openfootlab.com</a> · <a href="tel:15615327120">561.532.7120</a></p></section>
 </main><footer><div className="brand"><span className="mark">OF</span><span>OPENFOOTLAB</span></div><p>Personalized foot support, built with care.</p><p>© 2026 OpenFootLab · Jupiter, Florida</p></footer>{open&&<Intake close={()=>setOpen(false)}/>}</>
}
createRoot(document.getElementById('root')).render(<App/>);
